name: Deploy Portfolio to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Cloner le dépôt
        uses: actions/checkout@v3

      - name: 🚀 Déployer sur Railway
        run: |
          curl -X POST "https://backboard.railway.app/graphql/v2" \
          -H "Authorization: Bearer $7171fad1-8135-4830-b270-e706739d61fe" \
          -H "Content-Type: application/json" \
          --data '{ "query": "mutation { deploymentCreate(input: { projectId: \"honest-playfulness\" }) { id } }" }'